# Site settings
title: Wishardry's Red Room
description:
author: Wishardry
email: wishardry@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure - creates clean URLs without dates
permalink: /:title/

# Social media (optional - delete lines you don't use)

# Pinned posts - edit this list to change what appears at the top of homepage
# Use the URL slug (the part after your domain, like /beginnings/ or /A-River-Not-A-Wall/)
pinned_posts:
  - /beginnings/
  - /A-River-Not-A-Wall/
  - /resources/

# Minima theme settings
minima:
  skin: classic # Options: classic, dark, solarized-dark, solarized
  date_format: "%B %-d, %Y"

# Site-wide settings
show_excerpts: true # Show post excerpts on homepage
google_analytics: G-CZR3S9566M

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
