# Site settings
title: Wishardry's Red Room
description:
author: Wishardry
email: wishardry@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure
permalink: /:year/:month/:day/:title/

# Social links (optional)
twitter_username: 
github_username: 

# Minima theme settings
minima:
  skin: classic
  date_format: "%B %-d, %Y"
