# Site settings
title: Wishardry's Red Room
description:
author: Wishardry
email: wishardry@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure - creates clean URLs without dates
permalink: /:title/

# Social media (optional - delete lines you don't use)


# Minima theme settings
minima:
  skin: classic # Options: classic, dark, solarized-dark, solarized
  date_format: "%B %-d, %Y"

# Site-wide settings
show_excerpts: true # Show post excerpts on homepage
google_analytics: G-CZR3S9566M

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
